name: Build UnrealMemoryTools
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install tools
        run: sudo apt update && sudo apt install cmake ninja-build -y

      - name: Setup NDK r26b
        uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r26b

      - name: Fix hardcode path
        run: sed -i "s|set(NDK_PATH E:/ndk/android-ndk-r29)|set(NDK_PATH ${{ steps.ndk.outputs.ndk-path }})|" CMakeLists.txt

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS="-fno-char8_t -Wno-ambiguous-operator"

      - name: Compile
        run: cmake --build build -j$(nproc)

      - name: Pack
        run: zip UnrealMemoryTools.zip outputs/arm64-v8a/UnrealMemoryTools

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Output
          path: UnrealMemoryTools.zip
